FROM python:3.12-slim
WORKDIR /app
RUN pip install psycopg2-binary
COPY app.py .
ENTRYPOINT ["python", "app.py"]


### Get docker to run the DB
##docker run -d --name LogDB -e POSTGRES_PASSWORD=password -p 5432:5432 postgres:15-alpine

## Stop DB
##docker stop LogDB
##remove DB
##docker rm LOGDB
# Build and run app
##docker build -t python_app .
##docker run --rm python_app