FROM python:3.12-slim
WORKDIR /app
COPY app.py .
ENTRYPOINT ["python", "app.py"]

##docker build -t my-python-app .
##docker volume create mydata
##docker run -d --name my-python-container -v mydata:/app my-python-app
